@startuml GeoTab
title Отология GeoTab
skinparam hardwritten true


'Определение классов онтологии
class GeoTab{
}

class ТелематическоеУстройство{
  +ЧислоОборотовДвигателя
  +НапряжениеАккумулятора
  +ВключеннаяСигнальнаяЛампаДвигателя
  +ИспользованиеРемнейБезопасности
  +Одометр
  +ВремяРаботыДвигателя
  +НеисправностиВыбросов
  +ИдентификационныйНомерАвтомобиля(VIN)
  +СерийныйНомерТелематУстройства
}

class Одометр{
}

'Поездка определяется как активность актива с момента начала движения до момента остановки.
class Поездка{
  +Категория
  +ВремяНачала
  +ВремяОкончания
  +СтартоваяТочка
  +КонечнаяТочка
  +Зона
  +Дистанция
  +Скорость
  +ТекущиеИсключения
}

class ИсторияПоездок{
  +ОбщаяПродолжительностьОстановок
  +ОбщаяПродолжительностьВождения
  +ОбщееРасстояние
  +Остановки
}

class Карта{
  +Провайдер
  +ТипКарты
  +Легенда
  +Трафик
  +Зоны
  +Активы
  +Водители
  +Адреса
  +Клиенты
  +НомерныеЗнаки
}

class Дорога{
  +ОграничениеСкорости
  +Зона
  +Адрес
}


class Актив {
  +Тип
  +НазваниеАктива
  +СерийныйНомерТелематУстройства
  /'Активный с устройством слежения.
  Активен без устройства слежения.
  Архивировано.'/
  +Статус
  +VINномер
  /'Свойства ниже появляются при отображении актива на карте'/
  +Местоположение
  +Размер
  +ДатаВремяПоследнегоИзмененияСтатуса
  +Водитель
  +КонтактнаяИнформацияВодителя
  +НазваниеЗоны
  +Пробег
  +РасходТоплива
  +Комментарий
}

class Электромобиль{
  +УровеньЗаряда
  +СтатусЭлектромобиля
}

class ОбычноеТранспортноеСредство{
  +КоличествоТоплива
}

'Зона - это виртуальный периметр вокруг реальной области, представляющей интерес.
class Зона{
  +НазваниеЗоны
  +АдресЗоны
  +Ссылка
  +Комментарий
  +ТипЗоны
  +Цвет
  +ВидимостьНаКарте
  +Форма
  +Размер
  +Диаметр
  +НаличиеОстановокВЗоне
  +АктивнаС
  +ДатаОкончания
  +Состояние
}

class Пользователи{
  +Имя
  +Фамилия
  +АдресЭлектроннойПочты
  +ДатаПоследнегоДоступа
  +УровеньДопуска
  +ТипПользователя
  +Группа
}

class Водители{
  +ID
  +НомерВУ
  +ШтатПолученияЛицензии
  +РабочийСтатус
  +КлючиВодителя
  +НомерТелефона
}

class Клиенты{
}

class Партнеры{
  +НазваниеКомпании
  +АдресКомпании
  +НомерТелефона
  +Вебсайт
  +ГосОрганизация
  +ИмяПартнера
  +РазрешитьПартнеруДоступБД
  +ДиапазонСкорости
  +ЛьготныйПериод
  +Персонализация
  +ПочтаОтправителя
}


class Техподдержка{
}

class ОнлайнЧат{
}

class РабочиеЧасы{
  +ЧасыРаннегоВыезда
  +ПоздниеЧасыПрибытия
  +ЧасыОбеда
  +СтандартныеЧасы
  +ПользовательскийНаборЧасов
}

'Позволяет устанавливать определенные даты в качестве праздничных дней для ваших работников
class РабочиеПраздники{
}

class Маршрут{
  +НазваниеМаршрута
  +ТипМаршрута
  +Комментарий
}

class ПутеваяТочка{
  +Порядок
  +Адрес
  +Зона
}

class ИсторияПоказанийОдометра{
}


class Дашборд{
}

class ПриложениеУправлениеАвтопарком{
}

class Маркетплейс{
}

'Решение для отправки помощи на дороге автомобилям, попавшим в беду.
class ПриложениеПомощьНаДорогах{
}

class ПриложениеDriveApp {
}

class ПользовательскиеОтчеты{
  +ТипОтчета
  +Название
  +ДатаСоздания
  +ДатаОкончанияСрокаДействия
  +Размер
  +Параметры
}

class ВстроенныеОтчеты{
}

class ИнтерактивныеГрафики{
}

'ВстроенныеОтчеты
'Отображает продолжительность холостого хода и процент холостого хода. 
struct НарушенияРежимаХолостогоХода{
}

'Помогает следить за состоянием телематических устройств. 
struct ОтчетСторожевогоУстройства{
  +НазваниеАктива
  +ГруппаАктива
  +ПоследнийИзвестныйАдрес
  +ДатаПоследнейСвязи
  +ДниСМоментаПеремещения
  +ДниСМоментаСообщения
  +СерийныйНомер
  +Статус
}     

'Показывает пройденное расстояние всего автопарка. 
struct ИспользованиеАвтопарка{
}       

'Представляет данные о пройденном расстоянии всего автопарка.
struct ТрендРасстоянияДоАвтопарка{
  +ПройденноеРасстояние
}         

'Виды интерактивных графиков  
circle Деятельность
circle ДвигательИТехОбслуживание    
circle ЗоныИСообщения
circle ПравилаИГруппы

'Деятельность 
struct ПрофильСкорости{
  +СкоростьДвиженияОбъекта
  +ИзвестноеОграничениеСкорости
  +ПредполагаемоеОграничениеСкорости
}

struct СкоплениеВодителей{
  +УчаствующиеВодители
  +ВремяПрибытия
  +ВремяОтъезда
  +ПродолжительностьСкопления
  +МестоположениеАктива
}

struct УчетРабочегоВремени{
  +ДниАктивности
  +ОбщаяПродолжительностьРаботы
  +ВремяВождения
  +ВремяПростоя
}

struct IFTA{
  +ДиапазонДат
  +Активы
  +Водители
  +ВремяВъезда
  +ВремяВыезда
  +ПоказанияОдометраДляКаждогоВодителя
  +ОбщееРасстояниеДляКаждогоВодителя
}

struct ЖурналДанныхИКоллизий{
  +ДиапазонДат
  +Активы
}

'Двигатель и техническое обслуживание
struct Неисправности{
  +КодНеисправности
  +Описание
  +ТекущееСостояние
  +ЗарегистрированноеВремя
  +ИсточникНеисправности
  +ПротоколИсточника
  +ДопСведения
  +Серьезность
  +Контроллер
}

/'
В отчете отображается расход топлива и экономия топлива для обычных автомобилей, 
а также электрическая энергия 
и экономию электроэнергии для электромобилей.
'/
struct ИспользованиеТопливаИЭнергии{
  +Актив
  +ЭкономияТоплива/ЭлектрическойЭнергии
  +РасходТоплива
  +РасходЭлектроэнергии
  +Дистанция
  +ПериодВремени
}

struct ОтчетЗаправки{
  +Дата
  +Адрес
  +ОбычноеТранспортноеСредство
  +Водитель
  +ЭкономияТоплива
  +ДобавленныйОбъем
  +Одометр
}

struct ОтчетЗарядкиЭлектромобиля{
  +Электромобиль
  +ПериодЗарядки
  +ПродолжительностьЗарядки
  +Адрес
  +ПроцентЗаряда
  +ЭкономияЭлектроэнергии
  +ДобавленнаяЭлектроэнергия
}

struct ИсторияТехОбслуживания{
}


struct СостояниеАккумлятораЭлектромобиля{
  +Актив
  +МаркаМодельГод
  +ДатаОбнаружения
  +ОдометрНаДатуОбнаружения
  +ОбнаруженнаяПолезнаяЕмкость
  +СостояниеАккумулятораЭлектромобиля
  +ПолезнаяПервоначальнаяЕмкость
}

struct ЗарядХодаЭлектромобиля{
  +Дата
  +ЧасовойПояс
  +RangeCapabilityUnit
  +ЕдиницаЭкономииЭлектроэнергии 
  +ЕдиницаИзмеренияОбнаруженнойПолезнойЕмкостиАккумулятора
  +Актив 
  +Группа
  +Марка
  +Модель
  +Год
  +ДатаОбнаружения
  +ВозможностьОбнаруженногоДиапазона
  +ОбнаруженнаяЭкономияЭлектроэнергии
  +ОбнаруженнаяПолезнаяЕмкостьБатареи
}

'ЗоныИСообщения
struct ПосещенияЗонКлиентами{
  +НазваниеЗоны
  +ВремяПрибытия
  +ПродолжительностьОстановки
  +ВремяОтправления 
}

struct ПлановыеИФактическиеМаршруты{
  +ЗапланированныеМаршруты
  +ЗапланированныеПоездки
  +ОпозданиеВодителя
  +ПропускиОстановок
  +ОжидаемаяПродолжительностьОстановки
  +Расстояние
}

struct СводкаПоМаршруту{
  +Период
  +Активы
}


'ПравилаИГруппы
struct ОтчетИсключения{
}

class Исключения {
}

'Определение отношений между классами
GeoTab                          --> ПриложениеУправлениеАвтопарком  : содержит
GeoTab                          *-- ПриложениеЦентрТехОбслуживания  : надстройка
GeoTab                          *-- Маркетплейс                     : надстройка
GeoTab                          *-- Техподдержка
GeoTab                          o-- Одометр                         : надстройка
GeoTab                          o-- Тахограф                        : надстройка
GeoTab                          *-- ПриложениеDriveApp              : надстройка

Одометр                         --> ИсторияПоказанийОдометра

ТелематическоеУстройство        --> ИсторияПоказанийОдометра        : автоматически записывает
ТелематическоеУстройство        --> ПриложениеУправлениеАвтопарком  : работает с
ТелематическоеУстройство        --> ПриложениеDriveApp              : работает с


ПриложениеЦентрТехОбслуживания  --> НапоминаниеОТехОбслуживании : позволяет планировать
ПриложениеЦентрТехОбслуживания  --> ЗаписиТехОбслуживания       : содержит
ЗаписиТехОбслуживания           --> Актив                       : содержит инф о 
НапоминаниеОТехОбслуживании     --> Актив                       : относится к
Пользователи                    --> НапоминаниеОТехОбслуживании : редактируют 


ПриложениеУправлениеАвтопарком  --> Пользователи                : содержит инф о
ПриложениеУправлениеАвтопарком  --> Дашборд                     : содержит
ПриложениеУправлениеАвтопарком  --> Карта                       : содержит
ПриложениеУправлениеАвтопарком  --  ПриложениеDriveApp
ПриложениеУправлениеАвтопарком  --> РабочиеЧасы                 : содержит
ПриложениеУправлениеАвтопарком  --> РабочиеПраздники            : содержит
ПриложениеУправлениеАвтопарком  --> Правила                     : содержит

ПриложениеПомощьНаДорогах       --* Маркетплейс                 : надстройка
ПриложениеПомощьНаДорогах       --> Актив                       : назначает на запрос
note on link #lightblue
отправка помощи на дороге 
автомобилям, 
попавшим в беду
end note

Пользователи                 <|-- Водители
Пользователи                 <|-- Клиенты
Пользователи                 <|-- Партнеры
Пользователи                 <|-- Сотрудники 

Актив                        <|-- Электромобиль                : наследует 
Актив                        <|-- ОбычноеТранспортноеСредство  : наследует 
Актив                        o-- ТелематическоеУстройство      : установлено на
Актив                        o-- Тахограф                      : установлен на
Актив                        o-- Одометр                       : установлен на
 
Дашборд                      *-- ИнтерактивныеГрафики          : включает 
note on link #lightblue
Ряд отчетов, 
который можно отобразить на дашборде
end note

Дашборд                     *-- ВстроенныеОтчеты               : включает 
note on link #lightblue
Ряд отчетов, 
отображаемыей на дашборде по умолчанию
end note

Дашборд                     *-- ПользовательскиеОтчеты        : включает 

ИсторияПоездок              --> Поездка                       : содержит

Карта                       --> Дорога                        : отображает
Карта                       --> Поездка                       : отображает
Карта                       --> Зона                          : отображает

Актив                       --> Зона                          : отправить на
Водители                    --> Актив                         : назначается на
Маршрут                     --> Актив                         : назначается на
Поездка                     --> Актив                       
Маршрут                     *-- ПутеваяТочка                  : состоит из

Сообщения                   -- Водители                       : отправка/принятие
Сообщения                   -- ПриложениеDriveApp             : отправка/принятие

Техподдержка                --> ОнлайнЧат                     : содержит
Техподдержка                --> КонтактнаяИнформация          : содержит

КонтактнаяИнформация        --> Партнеры                      : содержит инф о 
Клиенты                     --> КонтактнаяИнформация          : просматривают
Клиенты                     --> ОнлайнЧат                     : пишут в

ВстроенныеОтчеты            --> НарушенияРежимаХолостогоХода
ВстроенныеОтчеты            --> ОтчетСторожевогоУстройства
ВстроенныеОтчеты            --> ИспользованиеАвтопарка
ВстроенныеОтчеты            --> ТрендРасстоянияДоАвтопарка

ИнтерактивныеГрафики        --> Деятельность
ИнтерактивныеГрафики        --> ДвигательИТехОбслуживание
ИнтерактивныеГрафики        --> ЗоныИСообщения
ИнтерактивныеГрафики        --> ПравилаИГруппы

Деятельность                --> ПрофильСкорости
Деятельность                --> СкоплениеВодителей
Деятельность                --> УчетРабочегоВремени
Деятельность                --> IFTA
Деятельность                --> ЖурналДанныхИКоллизий

ДвигательИТехОбслуживание   --> Неисправности
ДвигательИТехОбслуживание   --> ИспользованиеТопливаИЭнергии
ДвигательИТехОбслуживание   --> ОтчетЗаправки
ДвигательИТехОбслуживание   --> ОтчетЗарядкиЭлектромобиля
ДвигательИТехОбслуживание   --> ИсторияТехОбслуживания
ДвигательИТехОбслуживание   --> СостояниеАккумлятораЭлектромобиля
ДвигательИТехОбслуживание   --> ЗарядХодаЭлектромобиля


ЗоныИСообщения              --> ПосещенияЗонКлиентами
ЗоныИСообщения              --> ПлановыеИФактическиеМаршруты
ЗоныИСообщения              --> СводкаПоМаршруту

' Правила и группы
ПравилаИГруппы              --> ОтчетИсключения
ОтчетИсключения             --> Исключения                    : содержит 
Исключения                  --> Правила                       : отображают нарушение 
Исключения                  --> Уведомления                   : вызывают
Уведомления                 --> ПриложениеDriveApp            : отображаются
Правила                     --> Группы                        : назначаются на 
Водители                    --> Группы                        : входят в 
Актив                       --> Группы                        : входит в 
Зона                        --> Группы                        : входит в 


УчетРабочегоВремени         --> РабочиеЧасы                   : использует
УчетРабочегоВремени         --> РабочиеПраздники              : использует
УчетРабочегоВремени         --> Актив                         : фиксирует
УчетРабочегоВремени         --> Водители                      : фиксирует
IFTA                        --> ИсторияПоказанийОдометра      : основывается на

СводкаПоМаршруту            --> Актив                         : просматривается по
СводкаПоМаршруту            --> Маршрут                       : просматривается по
note on link #lightblue
отчет полезен для
определения, ездят ли 
несколько активов по одним 
и тем же маршрутам 
end note

@enduml
